import './parts/header.js';
import './parts/mobmenu.js';
import './parts/mobmenu.js';
import './parts/modal.js';
import './parts/banner.js';
import './parts/forms.js';
import './parts/scroll.js';
import './parts/ambass.js';
import './parts/moreblock.js';
